// profile_summary: everything derives from the workspace files plus the
// public referential — coverage, triggered tensions, personal-graph checks,
// open work — and the generated summary.md portrait.

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { pickLocale, poleWeight, type Corpus, type Locale } from "./corpus.js";
import type { Workspace } from "./workspace.js";

/* eslint-disable @typescript-eslint/no-explicit-any */

const STALE_DAYS = 90;

function predicateHolds(corpus: Corpus, entries: any, cond: any): boolean {
  const entry = entries[cond.axisId];
  if (!entry?.value) return false;
  const axis = corpus.axes.get(cond.axisId);
  if (!axis) return false;
  if (cond.predicate.kind === "scalarRange") {
    return (
      entry.value.kind === "scalar" &&
      entry.value.value >= cond.predicate.min &&
      entry.value.value <= cond.predicate.max
    );
  }
  return poleWeight(axis, entry.value, cond.predicate.poleId) >= cond.predicate.min;
}

export function computeSummary(corpus: Corpus, ws: Workspace, locale: Locale) {
  const profile = ws.profile();
  const entries: Record<string, any> = profile.entries;
  const axesList = [...corpus.axes.values()];
  const now = Date.now();

  const byRelation: Record<string, { touched: number; total: number }> = {};
  for (const axis of axesList) {
    byRelation[axis.relation] ??= { touched: 0, total: 0 };
    byRelation[axis.relation].total += 1;
    if (entries[axis.id]) byRelation[axis.relation].touched += 1;
  }

  const positioned = Object.entries(entries).filter(([, e]: any) => e.status === "POSITIONED");
  const stale = Object.entries(entries)
    .filter(([, e]: any) => now - Date.parse(e.updatedAt) > STALE_DAYS * 24 * 3600 * 1000)
    .map(([axisId]) => axisId);

  const tensionsTriggered = corpus.tensions
    .filter(
      (rule) => predicateHolds(corpus, entries, rule.a) && predicateHolds(corpus, entries, rule.b),
    )
    .map((rule) => ({
      id: rule.id,
      axes: [rule.a.axisId, rule.b.axisId],
      explanation: pickLocale(rule.explanation, locale),
    }));

  const beliefs = ws.list("beliefs");
  const ungroundedPrescriptive = beliefs
    .filter((b) => b.status === "HELD" && b.mode === "PRESCRIPTIVE" && !(b.grounds?.length))
    .map((b) => b.id);

  // Refs written against another corpus version: surfaced, never a failure.
  const danglingRefs = ws.danglingRefs();

  return {
    coverage: {
      touched: Object.keys(entries).length,
      positioned: positioned.length,
      totalAxes: axesList.length,
      core: {
        touched: axesList.filter((a) => a.core && entries[a.id]).length,
        total: axesList.filter((a) => a.core).length,
      },
      byRelation,
    },
    majorPositions: Object.entries(entries)
      .filter(([, e]: any) => e.salience === "MAJOR")
      .map(([axisId, e]: any) => ({
        axisId,
        status: e.status,
        value: e.value,
        rationale: e.rationale,
      })),
    tensionsTriggered,
    personalGraph: { ungroundedPrescriptiveBeliefs: ungroundedPrescriptive },
    staleEntries: stale,
    openWork: {
      activeInquiries: ws.list("inquiries", { status: "ACTIVE" }).map((q) => q.id),
      fuzzyConcepts: ws
        .list("concepts")
        .filter((c) => c.clarity === "FUZZY" || c.clarity === "UNDEFINED")
        .map((c) => c.id ?? c.ref),
    },
    ...(danglingRefs.length > 0 ? { danglingRefs } : {}),
  };
}

const T = {
  title: { en: "My philosophy — generated portrait", fr: "Ma philosophie, portrait généré" },
  doNotEdit: {
    en: "Generated by philoscopia-mcp after each session. Do not edit: your files are the source.",
    fr: "Généré par philoscopia-mcp après chaque session. Ne pas éditer : vos fichiers font foi.",
  },
  coverage: { en: "Coverage", fr: "Couverture" },
  coverageLine: {
    en: (t: number, p: number, total: number, c: string) =>
      `${t} axes touched (${p} positioned) out of ${total} · core axes: ${c}`,
    fr: (t: number, p: number, total: number, c: string) =>
      `${t} axes abordés (${p} avec position) sur ${total} · axes nodaux : ${c}`,
  },
  positions: { en: "My structuring positions", fr: "Mes positions structurantes" },
  tensions: { en: "Tensions to examine", fr: "Tensions à examiner" },
  beliefs: { en: "Strongly held beliefs", fr: "Croyances fermes" },
  inquiries: { en: "Open questions", fr: "Questions ouvertes" },
  practices: { en: "Current practices", fr: "Pratiques en cours" },
  recent: { en: "Moved recently", fr: "A bougé récemment" },
} as const;

export function renderSummaryMd(corpus: Corpus, ws: Workspace, locale: Locale): string {
  const summary = computeSummary(corpus, ws, locale);
  const profile = ws.profile();
  const axisLabel = (id: string) => pickLocale(corpus.axes.get(id)?.label ?? id, locale);

  const lines: string[] = [`# ${T.title[locale]}`, "", `*${T.doNotEdit[locale]}*`, ""];

  lines.push(`## ${T.coverage[locale]}`, "");
  lines.push(
    T.coverageLine[locale](
      summary.coverage.touched,
      summary.coverage.positioned,
      summary.coverage.totalAxes,
      `${summary.coverage.core.touched}/${summary.coverage.core.total}`,
    ),
    "",
  );

  if (summary.majorPositions.length > 0) {
    lines.push(`## ${T.positions[locale]}`, "");
    for (const pos of summary.majorPositions) {
      lines.push(`- **${axisLabel(pos.axisId)}**${pos.rationale ? ` : ${pos.rationale}` : ""}`);
    }
    lines.push("");
  }

  if (summary.tensionsTriggered.length > 0) {
    lines.push(`## ${T.tensions[locale]}`, "");
    for (const tension of summary.tensionsTriggered) {
      lines.push(`- ${tension.axes.map(axisLabel).join(" × ")} : ${tension.explanation}`);
    }
    lines.push("");
  }

  const strong = ws.list("beliefs").filter((b) => b.status === "HELD" && b.adherence === "STRONG");
  if (strong.length > 0) {
    lines.push(`## ${T.beliefs[locale]}`, "");
    for (const belief of strong) lines.push(`- ${belief.statement}`);
    lines.push("");
  }

  const active = ws.list("inquiries", { status: "ACTIVE" });
  if (active.length > 0) {
    lines.push(`## ${T.inquiries[locale]}`, "");
    for (const inquiry of active) lines.push(`- ${inquiry.statement}`);
    lines.push("");
  }

  const practices = ws.list("practices");
  if (practices.length > 0) {
    lines.push(`## ${T.practices[locale]}`, "");
    for (const practice of practices) {
      lines.push(`- ${practice.statement}${practice.frequency ? ` (${practice.frequency})` : ""}`);
    }
    lines.push("");
  }

  const recent = Object.entries(profile.entries as Record<string, any>)
    .flatMap(([axisId, e]) => e.history.map((h: any) => ({ axisId, at: h.at })))
    .sort((a, b) => b.at.localeCompare(a.at))
    .slice(0, 5);
  if (recent.length > 0) {
    lines.push(`## ${T.recent[locale]}`, "");
    for (const move of recent) lines.push(`- ${move.at.slice(0, 10)} · ${axisLabel(move.axisId)}`);
    lines.push("");
  }

  const content = lines.join("\n");
  writeFileSync(join(ws.dir, "summary.md"), content);
  return content;
}
